-- drop tables
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS snippets CASCADE;
DROP TABLE IF EXISTS channels_types CASCADE;
DROP TABLE IF EXISTS users_channels CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS logs CASCADE;